# Edit or delete this file to control the "Sponsor" button on the GitHub repo.
# Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# Uncomment and fill in any of these once you set up the corresponding accounts:

# github: [Ranzim]
# ko_fi: Ranzim
# buy_me_a_coffee: Ranzim
# polar: Ranzim
# custom: ["https://yoursite.example/donate"]
